### ISSUE TITLE
souzou 1998

### ISSUE THREAD

**Issue by ole-peters** [LMLhub/Discounting#6]
re-write the paragraph, make it more understandable, explain what the basic idea is (first part of current paragraph), delete excessive detail (last part of current paragraph).

**Comment by diomavro** [comment]
Put the last one in a footnote: 
The reasoning behind the model of~\citet{sozou1998hyperbolic}, for example, is that agents have some belief about how often an event occurs and as time elapses without the event occurring they gradually downwardly revise their belief about said probability. The formal model uses beliefs about the hazard rate of a random event. The belief is revised through Bayesian updating, thus, the longer an event does not occur, the more likely it is that it will not occur (decreasing estimated hazard rate). In other words, the agents have some prior on the arrival rate of the event, and the longer they wait without observing the event the more they judge that the arrival rate must be small. \footnote{The procedure used is relatively simple, they take Laplace transform of the survival probability, and show that if the survival probability is equal to the hyperbolic discount rate, the agents' prior must be an exponential distribution}
