### ISSUE TITLE
summarize Radner reference

### ISSUE THREAD

**Issue by ole-peters** [LMLhub/Discounting#7]
Ole couldn't understand this paragraph - rephrase and check if it fits, otherwise leave out.

**Comment by diomavro** [comment]
The growth approach we employ is a generalization of work by \citet{Radner1998} who takes a survival approach to firms. If a firm maximizes growth, she is also maximizing her survival probability but if she merely chooses to optimize her survival probability she does not neccesarily optimize growth. Radner considers two firm policies, a policy where firms maximize their expected withdrawal rate and a policy where firms maximize their survival probability, the idea is that firms that maximize the withdrawal rate will choose a higher variance which results in a higher probability of ruin.

**Comment by bermanjoe** [comment]
I see why mentioning Radner is relevant to our paper, but having no risk in our model makes the comparison to his approach confusing. so I'm not sure about it.

**Comment by diomavro** [comment]
My reasoning behind why I want it is a sort of answer to the question: why growth?
The answer is that growth theoretically implies a different distribution of firms than profit maximization. It's just one of the questions/comments I expect lots of "but people/firms don't maximize growth, its silly"

I'm not really that adamant about it, so if you don't like it, we should just drop it.

**Comment by bermanjoe** [comment]
It's an important point, and probably the main criticism we would get. I still think the best answer is: "No knowledge of the decision-maker's psychology is required in this setup -- only the postulate that she prefers her wealth to grow faster rather than slower."

I wish we could have used references to support this as well, but it seems to me that Radner's point is too convoluted.

**Comment by ole-peters** [comment]
I think the paper is quite far from what we're doing. It starts by saying
people maximize utility and firms maximize profits. This, it is claimed, is
in all the textbooks.

Without time in there, what do any of these terms mean? Maximize profit...
It always has to be some form of a rate, otherwise it doesn't work. Or
there's an implicit assumption of equal points in time in there. But it's
implicit, and we know how complicated the actual story is -- without making
it explicit, one is almost guaranteed to get it wrong. If I get to choose
between $100 profit in 10 years or $99 profit in a week, I'll go for the
$99 -- so I'm not maximizing profit. And what is profit? A dollar amount? A
dollar flow per time? A percentage return on investment per time?

He very vaguely knows that something is up and thinks "if I go bankrupt,
maybe that's not so good." Of course that's true, but it's a very extreme
and special thing to worry about. It's often not even part of the formal
problem setup (e.g. in GBM). So it all becomes very ad-hoc.

I skimmed the paper -- it feels like it can be summarized in 5 sentences.
There are lots of words and very few equations, and I'm not sure what's
actually done. It doesn't seem systematic or fundamental.

Maximizing survival probability is an ensemble concept (as is any
probability). It definitely invites trouble.

Ok, so here is my problem: this all seems like words to me. I want to know
what his model is, and what his claim/statement/point is. Not in essay form
but in formal form, mathematically. Otherwise we can't get a handle on it.

**Comment by ole-peters** [comment]
He is writing equations in words!!!! "c times h" etc.

He seems to be looking at Brownian motion and Geometric Brownian motion, but he's never heard of those terms. He adorns the models with some extras additive drift etc.

Why doesn't he write equations?

**Comment by ole-peters** [comment]
Ok, plowed my way through this paper. 
So, yes, he's looking at 
a) Brownian motion with drift and an absorbing boundary at zero, where the drift is split into a positive (profit) term and a negative (withdrawals) term. 
b) Geometric Brownian motion with drift, extended with an additive withdrawal term, again with an absorbing boundary at zero (which is reachable because of the withdrawal term).

He then asks what kind of behavior would be generated by two goals.
a) maximizing the probability of indefinite survival
b) maximizing the expectation value of discounted withdrawals (integrated with t->infty), his definition of "profit."

His point is that (not surprisingly) maximizing expected profit does not maximize indefinite survival probability. Of course, goal b) is sort of a straw-man by now: it's obviously silly to maximize the expected anything in the absence of ergodicity or access to the ensemble.

I don't think it's closely related to discounting. It does make some interesting points that seem to have been underemphasized in the literature (though nothing new to us). For instance - a firm that's about to die because it's almost run out of cash will choose maximum volatility out of desperation for survival. This is of course known from biology: animals take big risks in hunting/foraging if their life depends on it (e.g. birds with caloric reserves close to burn rate times duration of night).

His paper is interesting because he realizes that something about time (survival) is important, and is not the same as an expectation value (expected profit). So it's sort of a first peek in the direction of asking the ergodicity question. But the current paper is about discounting -- I would cite Radner as an example of an economist who noticed that something isn't quite right with using expectation values. But I don't think we need to do that in our current paper, especially since there's no risk in our setup.

**Comment by diomavro** [comment]
Oh wow, Ole actually you went to the end :). It's interesting that he didn't have the vocabulary, I almost feel bad for him. Alright then let's keep it out.  It is quite fun to frame this argument in evolutionary terms so that you can say, growth is actually what you should expect firms to be doing unless there is a lot of entry.
